//! `openai_api` backend through the real binary, against a mock OpenAI-compatible
//! server (prd.md `type: openai_api` fields, Error Handling exit 9/10/11).
//!
//! `litellm-rs`'s `install_default_runtime` is a process-wide `OnceLock`, so every
//! test here drives the real `ccm` binary as a *subprocess* (via `spawn_blocking`)
//! rather than linking litellm-rs into this test binary directly — each subprocess
//! gets a fresh `OnceLock`, and this also exercises the real argv/exit-code/stdio
//! surface end to end.

mod common;

use common::Fixture;
use predicates::prelude::PredicateBooleanExt;
use serde_json::json;
use wiremock::matchers::{header, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

fn api_yaml(base_url: &str, timeout_secs: u64, extra: &str) -> String {
    format!(
        "- name: OmniRoute\n  type: openai_api\n  prompt: default\n  base_url: {base_url}\n  model: gpt-5.4\n  api_key:\n    env: CCM_TEST_KEY\n  timeout: {timeout_secs}\n{extra}"
    )
}

const PROMPTS_YAML: &str =
    "default:\n  system: |\n    You are helpful.\n  template: write a commit message\n";

fn setup(fx: &Fixture) {
    fx.init_git();
    fx.write("a.txt", "hello\n");
    fx.stage("a.txt");
}

// `ccm` always requests a streaming completion (`completion_stream`) — see
// backend/openai.rs's module docs — because OmniRoute, the primary target,
// answers `/chat/completions` with SSE regardless of the request's `stream`
// field. So the mock server must speak SSE too: one `chat.completion.chunk`
// event carrying the full content in a single delta, followed by `[DONE]`.
fn success_response(content: &str) -> ResponseTemplate {
    let chunk = json!({
        "id": "cmpl-1",
        "object": "chat.completion.chunk",
        "created": 1,
        "model": "gpt-5.4",
        "choices": [
            {"index": 0, "delta": {"role": "assistant", "content": content}, "finish_reason": "stop"}
        ]
    });
    ResponseTemplate::new(200)
        .insert_header("content-type", "text/event-stream")
        .set_body_string(format!("data: {chunk}\n\ndata: [DONE]\n\n"))
}

#[tokio::test(flavor = "multi_thread")]
async fn happy_path_dry_run_prints_the_raw_message_to_stdout() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response("feat: add a.txt"))
        .expect(1)
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert
        .code(0)
        .stdout("feat: add a.txt")
        .stderr(predicates::str::contains(
            "Commit message generated by OmniRoute (gpt-5.4)",
        ));
}

#[tokio::test(flavor = "multi_thread")]
async fn resolved_model_is_folded_into_the_commit_message_generated_line() {
    // A routing gateway (e.g. OmniRoute) can resolve `entry.model` (an alias `ccm`
    // requested, "gpt-5.4" per api_yaml() below) to a different real upstream model —
    // the response chunk's own `model` field is what actually answered, and that's what
    // should be logged, not the configured alias.
    let server = MockServer::start().await;
    let chunk = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1,
        "model": "gemini-3.1-flash-lite",
        "choices": [{"index": 0, "delta": {"role": "assistant", "content": "feat: x"}, "finish_reason": "stop"}]
    });
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!("data: {chunk}\n\ndata: [DONE]\n\n")),
        )
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0).stderr(predicates::str::contains(
        "Commit message generated by OmniRoute (gpt-5.4 => gemini-3.1-flash-lite)",
    ));
}

#[tokio::test(flavor = "multi_thread")]
async fn a_leading_chunk_with_an_empty_model_does_not_shadow_a_later_real_one() {
    // litellm-rs's SSE transformer parses each chunk independently with no
    // carry-forward, so a leading chunk that omits `model` reports it as an empty
    // string rather than the real value a later chunk carries. collect_stream_text
    // must keep looking rather than latching onto that first, empty value.
    let server = MockServer::start().await;
    let first = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1, "model": "",
        "choices": [{"index": 0, "delta": {"role": "assistant"}, "finish_reason": null}]
    });
    let second = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1,
        "model": "gemini-3.1-flash-lite",
        "choices": [{"index": 0, "delta": {"content": "feat: x"}, "finish_reason": "stop"}]
    });
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!(
                    "data: {first}\n\ndata: {second}\n\ndata: [DONE]\n\n"
                )),
        )
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0).stderr(predicates::str::contains(
        "Commit message generated by OmniRoute (gpt-5.4 => gemini-3.1-flash-lite)",
    ));
}

#[tokio::test(flavor = "multi_thread")]
async fn omniroute_keepalive_chunks_do_not_shadow_the_real_resolved_model() {
    // Reproduces real OmniRoute wire behavior (captured via a local TCP proxy against
    // the live server while diagnosing an earlier bug report): while the real upstream
    // is still generating, OmniRoute sends periodic keep-alive chunks shaped exactly
    // like this — `id: "omniroute-keepalive"`, `model: "omniroute"` (not a real model,
    // just OmniRoute's own name), and a completely empty `delta` (no role, no
    // content). collect_stream_text must not treat "omniroute" as the resolved model;
    // it must keep waiting for a chunk whose delta actually carries a role or content.
    let server = MockServer::start().await;
    let keepalive = json!({
        "id": "omniroute-keepalive", "object": "chat.completion.chunk", "created": 0,
        "model": "omniroute",
        "choices": [{"index": 0, "delta": {}, "finish_reason": null}]
    });
    let real = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1,
        "model": "deepseek-v4-flash",
        "choices": [{"index": 0, "delta": {"role": "assistant", "content": "feat: x"}, "finish_reason": "stop"}]
    });
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!(
                    "data: {keepalive}\n\ndata: {keepalive}\n\ndata: {real}\n\ndata: [DONE]\n\n"
                )),
        )
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0).stderr(
        predicates::str::contains(
            "Commit message generated by OmniRoute (gpt-5.4 => deepseek-v4-flash)",
        )
        .and(predicates::str::contains("=> omniroute)").not()),
    );
}

#[tokio::test(flavor = "multi_thread")]
async fn a_multi_chunk_sse_stream_is_concatenated_into_one_message() {
    // Proves the accumulation loop in collect_stream_text actually accumulates across
    // chunks, rather than e.g. only keeping the last one — every other test here uses
    // success_response's single-chunk shortcut, which can't tell the two apart.
    let server = MockServer::start().await;
    let first = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1, "model": "gpt-5.4",
        "choices": [{"index": 0, "delta": {"role": "assistant", "content": "feat: "}, "finish_reason": null}]
    });
    let second = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1, "model": "gpt-5.4",
        "choices": [{"index": 0, "delta": {"content": "add a.txt"}, "finish_reason": "stop"}]
    });
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!(
                    "data: {first}\n\ndata: {second}\n\ndata: [DONE]\n\n"
                )),
        )
        .expect(1)
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0).stdout("feat: add a.txt");
}

#[tokio::test(flavor = "multi_thread")]
async fn api_key_becomes_a_bearer_header_and_headers_setting_becomes_a_real_header() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .and(header("authorization", "Bearer sk-test"))
        .and(header("x-custom-test", "hello"))
        .respond_with(success_response("feat: x"))
        .expect(1)
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    let extra = "  headers:\n    X-Custom-Test: hello\n";
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, extra),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0);
}

#[tokio::test(flavor = "multi_thread")]
async fn a_loopback_base_url_is_reachable_not_ssrf_blocked() {
    // Regression test for `endpoint_access: PrivateNetwork` in backend/openai.rs: the
    // default PublicOnly policy SSRF-blocks 127.0.0.1, which every test in this file
    // depends on NOT happening (wiremock always binds to loopback). If someone drops
    // that field, this (and every other test here) fails with a CallFailed SSRF error.
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response("feat: reachable"))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0).stdout("feat: reachable");
}

#[tokio::test(flavor = "multi_thread")]
async fn request_body_has_system_only_when_configured_and_user_is_template_plus_diff() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response("feat: x"))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(0);

    let requests = server.received_requests().await.unwrap();
    assert_eq!(requests.len(), 1);
    let body: serde_json::Value = requests[0].body_json().unwrap();
    assert_eq!(body["messages"][0]["role"], "system");
    assert_eq!(body["messages"][0]["content"], "You are helpful.\n");
    assert_eq!(body["messages"][1]["role"], "user");
    let user_content = body["messages"][1]["content"].as_str().unwrap();
    assert!(user_content.starts_with("write a commit message\n\n"));
    assert!(user_content.contains("a.txt"));
}

#[tokio::test(flavor = "multi_thread")]
async fn missing_api_key_env_var_is_exit_9_and_makes_no_request() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response("feat: x"))
        .expect(0)
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    // Deliberately not setting CCM_TEST_KEY.
    cmd.args(["--dry-run", "--config"]).arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(9);
}

#[tokio::test(flavor = "multi_thread")]
async fn a_non_2xx_plain_text_body_surfaces_only_the_status_accepted_limitation() {
    // prd.md requires the response body always be surfaced alongside the status for
    // exit 10. litellm-rs only does that when the body is a standard OpenAI-shaped
    // {"error": {"message": ...}} JSON envelope (see the sibling test below) — for
    // any other shape (plain text here), it discards the real body internally before
    // ccm's code ever sees it and reports only "Server error: <status>". Escalated to
    // and accepted by the user as a documented limitation of the mandated dependency
    // (see backend/openai.rs's module docs and findings.md) rather than switching off
    // litellm-rs. This test pins that *actual* behavior so a litellm-rs upgrade that
    // changes it is caught.
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(
            ResponseTemplate::new(500).set_body_string("OmniRoute: no upstream available"),
        )
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(10).stderr(
        predicates::str::contains("500")
            .and(predicates::str::contains("OmniRoute: no upstream available").not()),
    );
}

#[tokio::test(flavor = "multi_thread")]
async fn a_non_2xx_openai_shaped_json_error_body_surfaces_its_message() {
    // Probe: does litellm-rs surface the body when it IS a standard OpenAI-style
    // {"error": {...}} envelope, as opposed to the plain-text body in the test above?
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(ResponseTemplate::new(500).set_body_json(json!({
            "error": {"message": "OmniRoute: no upstream available", "type": "server_error"}
        })))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(10).stderr(predicates::str::contains(
        "OmniRoute: no upstream available",
    ));
}

#[tokio::test(flavor = "multi_thread")]
async fn a_slow_response_beyond_the_timeout_is_exit_10() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response("feat: x").set_delay(std::time::Duration::from_secs(5)))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 1, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir())
        .timeout(std::time::Duration::from_secs(20));
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(10);
}

#[tokio::test(flavor = "multi_thread")]
async fn connection_refused_is_exit_10() {
    // Bind a listener to get a genuinely free port, then drop it so nothing answers.
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    drop(listener);

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("http://127.0.0.1:{port}/v1"), 5, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(10);
}

#[tokio::test(flavor = "multi_thread")]
async fn an_empty_choices_array_is_exit_11() {
    let server = MockServer::start().await;
    let chunk = json!({
        "id": "cmpl-1", "object": "chat.completion.chunk", "created": 1, "model": "gpt-5.4",
        "choices": []
    });
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_string(format!("data: {chunk}\n\ndata: [DONE]\n\n")),
        )
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert.code(11);
}

#[tokio::test(flavor = "multi_thread")]
async fn non_json_garbage_response_is_exit_10_or_11() {
    // litellm-rs may classify a transport-level parse failure as either a call
    // failure or a malformed-response error; pin whichever it actually does today so
    // a future litellm-rs upgrade that changes it fails loudly here rather than
    // silently.
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(ResponseTemplate::new(200).set_body_string("not json at all"))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    let output = assert.get_output();
    let code = output.status.code().unwrap();
    assert!(code == 10 || code == 11, "unexpected exit code {code}");
}

#[tokio::test(flavor = "multi_thread")]
async fn blank_content_under_dry_run_is_exit_15_immediately() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response("   \n"))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert
        .code(15)
        .stdout(predicates::str::is_empty())
        .stderr(predicates::str::contains(
            "Generated empty message using OmniRoute (gpt-5.4)",
        ));
}

#[tokio::test(flavor = "multi_thread")]
async fn a_literal_empty_string_delta_is_exit_15_not_exit_11() {
    // A stream whose delta.content is `Some("")` genuinely carried content (an empty
    // message), which is a stage-8 blank-message concern (exit 15) — distinct from a
    // stream that never carried a delta.content field at all, which is exit 11
    // (MalformedResponse). collect_stream_text must track "did we see any content"
    // separately from the accumulated text to keep these apart.
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/chat/completions"))
        .respond_with(success_response(""))
        .mount(&server)
        .await;

    let fx = Fixture::new();
    setup(&fx);
    fx.write_config(
        &api_yaml(&format!("{}/v1", server.uri()), 30, ""),
        PROMPTS_YAML,
    );

    let mut cmd = fx.ccm();
    cmd.env("CCM_TEST_KEY", "sk-test")
        .args(["--dry-run", "--config"])
        .arg(fx.config_dir());
    let assert = tokio::task::spawn_blocking(move || cmd.assert())
        .await
        .unwrap();
    assert
        .code(15)
        .stdout(predicates::str::is_empty())
        .stderr(predicates::str::contains(
            "Generated empty message using OmniRoute (gpt-5.4)",
        ));
}
