//! Stage 7 of the check-order pipeline: message generation (prd.md "Selection" /
//! "Response cleanup" / Progress logging). Dispatches to the selected entry's backend,
//! applies the response-cleanup pass (`cleanup::clean_message` — strips a wrapping code
//! fence, then a wrapping pair of quotation marks), and logs the surrounding progress
//! lines. The blank-message hard failure (exit 15) is a stage-8 concern applied
//! differently by `--dry-run` vs. the default editor flow, so this module only logs
//! whether the *cleaned* result was blank and hands it back.

use crate::backend::MessageGenerator;
use crate::backend::agent_cli::AgentCliGenerator;
use crate::backend::openai::OpenAiGenerator;
use crate::cleanup;
use crate::config::model::{Entry, EntryKind, Prompts};
use crate::env::Environment;
use crate::error::CcmError;
use crate::progress;
use crate::prompt::ResolvedPrompt;
use std::path::Path;

/// Runs stage 7 to completion: resolves `entry`'s prompt, dispatches to its backend,
/// and logs the `Generating commit message using…` / `Raw/Cleaned message` (or `Raw
/// message`/`Cleaned message` when cleanup changed something) / `Generated empty
/// message…` / `Commit message generated by…` progress lines.
///
/// # Errors
/// A [`CcmError`] wrapping [`crate::error::GenerationError`] (exit 9, 10, or 11).
///
/// # Panics
/// If `entry.prompt` isn't a key of `prompts` — this is a broken invariant, not a
/// runtime condition: `config::validate::validate` guarantees every entry's `prompt`
/// references a real `prompts.yaml` key before an [`Entry`] can exist at all.
pub fn generate(
    entry: &Entry,
    prompts: &Prompts,
    diff: &str,
    cwd: &Path,
    env: &dyn Environment,
    stderr: &mut dyn std::io::Write,
) -> Result<String, CcmError> {
    let prompt_def = prompts
        .get(&entry.prompt)
        .expect("entry.prompt is validated against prompts.yaml keys during config validation");
    let resolved = ResolvedPrompt {
        system: prompt_def.system.as_deref(),
        template: &prompt_def.template,
    };

    let model = match &entry.kind {
        EntryKind::OpenaiApi(inner) => inner.model.as_str(),
        EntryKind::AgentCli(inner) => inner.model.as_str(),
    };

    let _ = progress::generating_commit_message(stderr, &entry.name, model);

    let outcome = match &entry.kind {
        EntryKind::OpenaiApi(inner) => OpenAiGenerator::new(inner, env).generate(&resolved, diff),
        EntryKind::AgentCli(inner) => AgentCliGenerator::new(inner, cwd).generate(&resolved, diff),
    }?;

    let message = cleanup::clean_message(&outcome.message);
    let _ = progress::raw_and_cleaned_message(stderr, &outcome.message, &message);
    let resolved_model = outcome.resolved_model.as_deref();

    if message.trim().is_empty() {
        let _ = progress::generated_empty_message(stderr, &entry.name, model, resolved_model);
    } else {
        let _ = progress::commit_message_generated(stderr, &entry.name, model, resolved_model);
    }
    let _ = progress::section_break(stderr);

    Ok(message)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::env::FakeEnvironment;
    use std::collections::HashMap;

    fn prompts_with(name: &str, system: Option<&str>, template: &str) -> Prompts {
        let mut map = HashMap::new();
        map.insert(
            name.to_string(),
            crate::config::model::Prompt {
                system: system.map(str::to_string),
                template: template.to_string(),
            },
        );
        map
    }

    fn agent_cli_entry(name: &str, prompt: &str, command: &str, args: &[&str]) -> Entry {
        Entry {
            name: name.to_string(),
            enabled: true,
            prompt: prompt.to_string(),
            kind: EntryKind::AgentCli(crate::config::model::AgentCliEntry {
                command: command.to_string(),
                model: "test-model".to_string(),
                args: args.iter().map(|s| (*s).to_string()).collect(),
                env: HashMap::new(),
                timeout_secs: 30,
            }),
        }
    }

    #[test]
    fn dispatches_to_agent_cli_and_logs_progress_for_a_non_blank_message() {
        let entry = agent_cli_entry("gemini", "default", "/bin/sh", &["-c", "echo feat: x"]);
        let prompts = prompts_with("default", None, "write it");
        let env = FakeEnvironment::new();
        let cwd = std::env::temp_dir();
        let mut stderr = Vec::new();
        let message = generate(&entry, &prompts, "diff", &cwd, &env, &mut stderr).unwrap();
        assert_eq!(message, "feat: x");
        let logged = String::from_utf8(stderr).unwrap();
        assert!(logged.contains("Generating commit message using gemini (test-model)…"));
        assert!(logged.contains(&format!(
            "{}\nfeat: x\n",
            progress::padded_header("Raw message")
        )));
        assert!(logged.contains(&format!(
            "{}\nfeat: x\n",
            progress::padded_header("Cleaned message")
        )));
        assert!(logged.contains("Commit message generated by gemini (test-model)"));
        assert!(!logged.contains("Generated empty message"));
    }

    #[test]
    fn raw_and_cleaned_message_collapses_to_one_dump_when_cleanup_is_a_no_op() {
        let entry = agent_cli_entry("gemini", "default", "/bin/sh", &["-c", "printf 'feat: x'"]);
        let prompts = prompts_with("default", None, "write it");
        let env = FakeEnvironment::new();
        let cwd = std::env::temp_dir();
        let mut stderr = Vec::new();
        let message = generate(&entry, &prompts, "diff", &cwd, &env, &mut stderr).unwrap();
        assert_eq!(message, "feat: x");
        let logged = String::from_utf8(stderr).unwrap();
        assert!(logged.contains(&format!(
            "{}\nfeat: x\n",
            progress::padded_header("Raw/Cleaned message")
        )));
        assert!(!logged.contains(&progress::padded_header("Raw message")));
    }

    #[test]
    fn raw_message_and_cleaned_message_differ_when_cleanup_actually_strips_something() {
        let entry = agent_cli_entry(
            "gemini",
            "default",
            "/bin/sh",
            &["-c", "printf '\"feat: add x\"'"],
        );
        let prompts = prompts_with("default", None, "write it");
        let env = FakeEnvironment::new();
        let cwd = std::env::temp_dir();
        let mut stderr = Vec::new();
        let message = generate(&entry, &prompts, "diff", &cwd, &env, &mut stderr).unwrap();
        assert_eq!(message, "feat: add x");
        let logged = String::from_utf8(stderr).unwrap();
        assert!(logged.contains(&format!(
            "{}\n\"feat: add x\"\n",
            progress::padded_header("Raw message")
        )));
        assert!(logged.contains(&format!(
            "{}\nfeat: add x\n",
            progress::padded_header("Cleaned message")
        )));
    }

    #[test]
    fn logs_generated_empty_message_for_a_blank_result() {
        let entry = agent_cli_entry("gemini", "default", "/bin/sh", &["-c", "printf '   '"]);
        let prompts = prompts_with("default", None, "write it");
        let env = FakeEnvironment::new();
        let cwd = std::env::temp_dir();
        let mut stderr = Vec::new();
        let message = generate(&entry, &prompts, "diff", &cwd, &env, &mut stderr).unwrap();
        // The unconditional trim (src/cleanup.rs) collapses all-whitespace raw output
        // to "" — the raw log line still shows the untrimmed "   " (logged before
        // cleanup runs), but the cleaned one is now blank.
        assert_eq!(message, "");
        let logged = String::from_utf8(stderr).unwrap();
        assert!(logged.contains(&format!(
            "{}\n   \n",
            progress::padded_header("Raw message")
        )));
        assert!(logged.contains(&format!(
            "{}\n\n",
            progress::padded_header("Cleaned message")
        )));
        assert!(logged.contains("Generated empty message using gemini (test-model)"));
        assert!(!logged.contains("Commit message generated by"));
    }

    #[test]
    fn a_backend_failure_surfaces_as_exit_10() {
        let entry = agent_cli_entry("gemini", "default", "/bin/sh", &["-c", "exit 3"]);
        let prompts = prompts_with("default", None, "write it");
        let env = FakeEnvironment::new();
        let cwd = std::env::temp_dir();
        let mut stderr = Vec::new();
        let err = generate(&entry, &prompts, "diff", &cwd, &env, &mut stderr).unwrap_err();
        assert_eq!(err.exit_code().as_u8(), 10);
    }
}
