//! Every step-by-step progress line `ccm` reports, centralized in one place (prd.md
//! "Progress logging"). All of it goes to stderr, never stdout, regardless of
//! `--dry-run` — stdout is reserved for the generated message under `--dry-run` and
//! `--gen-config`'s report. Each function is generic over `Write` so callers can target
//! the real stderr in production and an in-memory buffer in tests.
//!
//! The wording is implemented verbatim from the spec, including its inconsistencies
//! (e.g. `Generating commit message using <name> (<model>)…` uses a `…` ellipsis and no
//! colon, while `Generating diff using: <command>` uses a colon and no ellipsis) —
//! these read as intentional, not typos, so they're preserved rather than normalized.

use std::io::{self, Write};

pub fn enumerating_working_copy_files(
    out: &mut (impl Write + ?Sized),
    command: &str,
) -> io::Result<()> {
    writeln!(out, "Enumerating working-copy files using: {command}")
}

pub fn working_copy_files_enumerated(
    out: &mut (impl Write + ?Sized),
    command: &str,
) -> io::Result<()> {
    writeln!(out, "Working-copy files enumerated by: {command}")
}

pub fn generating_diff(out: &mut (impl Write + ?Sized), command: &str) -> io::Result<()> {
    writeln!(out, "Generating diff using: {command}")
}

pub fn diff_generated(out: &mut (impl Write + ?Sized), command: &str) -> io::Result<()> {
    writeln!(out, "Diff generated by: {command}")
}

pub fn generating_commit_message(
    out: &mut (impl Write + ?Sized),
    name: &str,
    model: &str,
) -> io::Result<()> {
    writeln!(out, "Generating commit message using {name} ({model})…")
}

pub fn generated_empty_message(
    out: &mut (impl Write + ?Sized),
    name: &str,
    model: &str,
) -> io::Result<()> {
    writeln!(out, "Generated empty message using {name} ({model})")
}

pub fn commit_message_generated(
    out: &mut (impl Write + ?Sized),
    name: &str,
    model: &str,
) -> io::Result<()> {
    writeln!(out, "Commit message generated by {name} ({model})")
}

pub fn committing_using(out: &mut (impl Write + ?Sized), command: &str) -> io::Result<()> {
    writeln!(out, "Committing using: {command}")
}

pub fn committed_using(out: &mut (impl Write + ?Sized), command: &str) -> io::Result<()> {
    writeln!(out, "Committed using: {command}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn captured(f: impl FnOnce(&mut Vec<u8>) -> io::Result<()>) -> String {
        let mut buf = Vec::new();
        f(&mut buf).unwrap();
        String::from_utf8(buf).unwrap()
    }

    #[test]
    fn enumeration_lines_match_spec_wording() {
        assert_eq!(
            captured(|w| enumerating_working_copy_files(w, "jj diff --summary")),
            "Enumerating working-copy files using: jj diff --summary\n"
        );
        assert_eq!(
            captured(|w| working_copy_files_enumerated(w, "jj diff --summary")),
            "Working-copy files enumerated by: jj diff --summary\n"
        );
    }

    #[test]
    fn diff_lines_match_spec_wording() {
        assert_eq!(
            captured(|w| generating_diff(w, "git diff --staged")),
            "Generating diff using: git diff --staged\n"
        );
        assert_eq!(
            captured(|w| diff_generated(w, "git diff --staged")),
            "Diff generated by: git diff --staged\n"
        );
    }

    #[test]
    fn message_generation_lines_match_spec_wording_including_ellipsis() {
        assert_eq!(
            captured(|w| generating_commit_message(w, "omniroute", "gpt-5.4")),
            "Generating commit message using omniroute (gpt-5.4)…\n"
        );
        assert_eq!(
            captured(|w| generated_empty_message(w, "omniroute", "gpt-5.4")),
            "Generated empty message using omniroute (gpt-5.4)\n"
        );
        assert_eq!(
            captured(|w| commit_message_generated(w, "omniroute", "gpt-5.4")),
            "Commit message generated by omniroute (gpt-5.4)\n"
        );
    }

    #[test]
    fn commit_lines_match_spec_wording() {
        assert_eq!(
            captured(|w| committing_using(w, "git commit -m ...")),
            "Committing using: git commit -m ...\n"
        );
        assert_eq!(
            captured(|w| committed_using(w, "git commit -m ...")),
            "Committed using: git commit -m ...\n"
        );
    }
}
