//! Every step-by-step progress line `ccm` reports, centralized in one place (prd.md
//! "Progress logging"). All of it goes to stderr, never stdout, regardless of
//! `--dry-run` — stdout is reserved for the generated message under `--dry-run` and
//! `--gen-config`'s report. Each function is generic over `Write` so callers can target
//! the real stderr in production and an in-memory buffer in tests.
//!
//! The wording is implemented verbatim from the spec, including its inconsistencies
//! (e.g. `Generating commit message using <name> (<model>)…` uses a `…` ellipsis and no
//! colon, while `Generating diff using: <command>` uses a colon and no ellipsis) —
//! these read as intentional, not typos, so they're preserved rather than normalized.
//!
//! `generated_empty_message`/`commit_message_generated` additionally take a
//! `resolved_model`, folded into the `(<model>)` portion as `<model> => <resolved>`
//! when it's known and differs: `openai_api` entries can route through a gateway (e.g.
//! OmniRoute) that picks the real upstream model dynamically, which the configured
//! `<model>` doesn't capture on its own. This isn't from prd.md's "Progress logging"
//! list — neither is [`raw_and_cleaned_message`], which dumps the backend's response
//! before and after `cleanup::clean_message` so a fence/quote-stripping bug (or an
//! LLM's own formatting choice) is visible directly in the log rather than only
//! inferable from the final message.

use std::io::{self, Write};

pub fn enumerating_working_copy_files(
    out: &mut (impl Write + ?Sized),
    command: &str,
) -> io::Result<()> {
    writeln!(out, "Enumerating working-copy files using: {command}")
}

pub fn working_copy_files_enumerated(
    out: &mut (impl Write + ?Sized),
    command: &str,
) -> io::Result<()> {
    writeln!(out, "Working-copy files enumerated by: {command}")
}

pub fn generating_diff(out: &mut (impl Write + ?Sized), command: &str) -> io::Result<()> {
    writeln!(out, "Generating diff using: {command}")
}

pub fn generating_commit_message(
    out: &mut (impl Write + ?Sized),
    name: &str,
    model: &str,
) -> io::Result<()> {
    writeln!(out, "Generating commit message using {name} ({model})…")
}

/// Logs the backend's response exactly as returned (`raw`) alongside the result of
/// running it through `cleanup::clean_message` (`cleaned`). When `cleanup` was a no-op
/// (the common case), collapses both into a single `Raw/Cleaned message` dump instead
/// of printing the same text twice; when it actually stripped a wrapping code fence or
/// quotes, prints `Raw message` and `Cleaned message` separately so the difference is
/// visible directly in the log rather than only inferable from the final message. Each
/// label sits on its own dash-padded header line (see [`padded_header`]) since the
/// message itself can span multiple lines, making it hard to tell where it starts
/// without one.
pub fn raw_and_cleaned_message(
    out: &mut (impl Write + ?Sized),
    raw: &str,
    cleaned: &str,
) -> io::Result<()> {
    if raw == cleaned {
        writeln!(out, "{}\n{raw}", padded_header("Raw/Cleaned message"))
    } else {
        writeln!(
            out,
            "{}\n{raw}\n{}\n{cleaned}",
            padded_header("Raw message"),
            padded_header("Cleaned message")
        )
    }
}

/// Centers `label` in a `-`-padded 40-column header line, e.g. `------ Raw message
/// ------`, so the label and its surrounding divider read as one line instead of two.
/// `pub(crate)` so callers (e.g. `generation.rs`'s tests) can build exact expected
/// strings instead of guessing at dash counts.
pub(crate) fn padded_header(label: &str) -> String {
    format!("{:-^40}", format!(" {label} "))
}

const DASH_LINE: &str = "----------------------------------------";

pub fn generated_empty_message(
    out: &mut (impl Write + ?Sized),
    name: &str,
    model: &str,
    resolved_model: Option<&str>,
) -> io::Result<()> {
    writeln!(
        out,
        "Generated empty message using {name} ({})",
        format_model(model, resolved_model)
    )
}

/// Preceded by a dash line to set the final message off from the `Raw message`/
/// `Cleaned message` dump right above it.
pub fn commit_message_generated(
    out: &mut (impl Write + ?Sized),
    name: &str,
    model: &str,
    resolved_model: Option<&str>,
) -> io::Result<()> {
    writeln!(
        out,
        "{DASH_LINE}\nCommit message generated by {name} ({})",
        format_model(model, resolved_model)
    )
}

/// Formats the `(<model>)` portion of a progress line, folding in the real upstream
/// model a gateway resolved `model` to (e.g. `gpt-5.4 => gemini-3.5-flash`) when that's
/// known and differs from what was configured. Plain `model` alone covers both the
/// common case (no gateway, or the gateway used exactly what was configured) and
/// `agent_cli` entries, which never resolve to anything else.
fn format_model(model: &str, resolved_model: Option<&str>) -> String {
    match resolved_model {
        Some(resolved) if resolved != model => format!("{model} => {resolved}"),
        _ => model.to_string(),
    }
}

pub fn committed_using(out: &mut (impl Write + ?Sized), command: &str) -> io::Result<()> {
    writeln!(out, "Committed using: {command}")
}

/// An `====` divider separating one group of progress lines (e.g. everything logged by
/// a single pipeline stage) from the next, so related lines visually cluster together
/// instead of running into one undifferentiated block. Heavier than the `----`
/// `DASH_LINE` used inside a single stage (e.g. around the message dump in
/// `raw_and_cleaned_message`), so the two nest into a two-level hierarchy rather than
/// competing for attention at the same weight. A single blank line turned out to be too
/// faint to register as a boundary when scrolling through a wall of stderr output.
pub fn section_break(out: &mut (impl Write + ?Sized)) -> io::Result<()> {
    writeln!(out, "{EQUALS_LINE}")
}

const EQUALS_LINE: &str =
    "================================================================================";

/// Logged once the tool picker's `fzf` front-end couldn't run (not on `$PATH`, no
/// controlling terminal, or any other failure — see `fzf::FzfOutcome::Unavailable`)
/// before `ccm` falls back to the numbered stdin prompt, so the fallback doesn't look
/// like it happened for no reason.
pub fn fzf_unavailable(out: &mut (impl Write + ?Sized), reason: &str) -> io::Result<()> {
    writeln!(
        out,
        "fzf unavailable ({reason}), falling back to the numbered picker"
    )
}

/// Logged once the interactive file picker (`fileselect.rs`, prd.md "Diff scope
/// resolution") resolves to an explicit, marked scope — a proper subset of the working
/// copy, or every candidate marked (which is still pinned as an explicit list, not
/// collapsed to `Selection::All` — see `fileselect.rs`) — so the log states what scope
/// the diff/commit that follows actually covers, the same spirit as `Working-copy
/// files enumerated by:` above but naming the *chosen* files rather than every changed
/// one. Not logged when the prompt was declined, or skipped outright (at most one
/// changed file).
pub fn files_selected(out: &mut (impl Write + ?Sized), files: &[String]) -> io::Result<()> {
    writeln!(
        out,
        "Diff scope restricted to {} file(s): {}",
        files.len(),
        files.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn captured(f: impl FnOnce(&mut Vec<u8>) -> io::Result<()>) -> String {
        let mut buf = Vec::new();
        f(&mut buf).unwrap();
        String::from_utf8(buf).unwrap()
    }

    #[test]
    fn enumeration_lines_match_spec_wording() {
        assert_eq!(
            captured(|w| enumerating_working_copy_files(w, "jj diff --summary")),
            "Enumerating working-copy files using: jj diff --summary\n"
        );
        assert_eq!(
            captured(|w| working_copy_files_enumerated(w, "jj diff --summary")),
            "Working-copy files enumerated by: jj diff --summary\n"
        );
    }

    #[test]
    fn diff_lines_match_spec_wording() {
        assert_eq!(
            captured(|w| generating_diff(w, "git diff --staged")),
            "Generating diff using: git diff --staged\n"
        );
    }

    #[test]
    fn message_generation_lines_match_spec_wording_including_ellipsis() {
        assert_eq!(
            captured(|w| generating_commit_message(w, "OmniRoute", "gpt-5.4")),
            "Generating commit message using OmniRoute (gpt-5.4)…\n"
        );
        assert_eq!(
            captured(|w| generated_empty_message(w, "OmniRoute", "gpt-5.4", None)),
            "Generated empty message using OmniRoute (gpt-5.4)\n"
        );
        assert_eq!(
            captured(|w| commit_message_generated(w, "OmniRoute", "gpt-5.4", None)),
            format!("{DASH_LINE}\nCommit message generated by OmniRoute (gpt-5.4)\n")
        );
    }

    #[test]
    fn raw_and_cleaned_message_collapses_to_one_dump_when_identical() {
        assert_eq!(
            captured(|w| raw_and_cleaned_message(w, "feat: add x", "feat: add x")),
            format!("{}\nfeat: add x\n", padded_header("Raw/Cleaned message"))
        );
    }

    #[test]
    fn raw_and_cleaned_message_prints_both_separately_when_cleanup_changed_something() {
        assert_eq!(
            captured(|w| raw_and_cleaned_message(w, "```\nfeat: add x\n```", "feat: add x")),
            format!(
                "{}\n```\nfeat: add x\n```\n{}\nfeat: add x\n",
                padded_header("Raw message"),
                padded_header("Cleaned message")
            )
        );
    }

    #[test]
    fn padded_header_centers_the_label_with_dashes_to_a_width_of_40() {
        let header = padded_header("Raw message");
        assert_eq!(header.len(), 40);
        assert!(header.contains(" Raw message "));
        assert!(header.starts_with('-'));
        assert!(header.ends_with('-'));
    }

    #[test]
    fn resolved_model_is_folded_into_the_model_parens_when_it_differs() {
        assert_eq!(
            captured(|w| commit_message_generated(
                w,
                "OmniRoute",
                "gpt-5.4",
                Some("gemini-3.1-flash-lite")
            )),
            format!(
                "{DASH_LINE}\nCommit message generated by OmniRoute (gpt-5.4 => gemini-3.1-flash-lite)\n"
            )
        );
        assert_eq!(
            captured(|w| generated_empty_message(
                w,
                "OmniRoute",
                "gpt-5.4",
                Some("gemini-3.1-flash-lite")
            )),
            "Generated empty message using OmniRoute (gpt-5.4 => gemini-3.1-flash-lite)\n"
        );
    }

    #[test]
    fn resolved_model_matching_the_configured_model_is_not_shown_twice() {
        assert_eq!(
            captured(|w| commit_message_generated(w, "OmniRoute", "gpt-5.4", Some("gpt-5.4"))),
            format!("{DASH_LINE}\nCommit message generated by OmniRoute (gpt-5.4)\n")
        );
    }

    #[test]
    fn section_break_writes_a_single_equals_line() {
        assert_eq!(captured(|w| section_break(w)), format!("{EQUALS_LINE}\n"));
    }

    #[test]
    fn commit_lines_match_spec_wording() {
        assert_eq!(
            captured(|w| committed_using(w, "git commit -m ...")),
            "Committed using: git commit -m ...\n"
        );
    }

    #[test]
    fn files_selected_line_matches_expected_wording() {
        assert_eq!(
            captured(|w| files_selected(w, &["a.rs".to_string(), "b.rs".to_string()])),
            "Diff scope restricted to 2 file(s): a.rs, b.rs\n"
        );
    }
}
